TestQ/Controllers/CompanyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TestQ.Model.Models;
using TestQ.Service.Interfaces;
using TestQ.Service.Services;

namespace TestQ.Controllers
{
    public class CompanyController : Controller
    {
        private IService<Company> companyService;
        public CompanyController()
        {
            companyService = CompanyService.Instance();
        }

        public ActionResult Create()
        {
            return View(new Company());
        }
        [HttpPost]
        public ActionResult Create(Company company)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    companyService.Add(company);
                    return RedirectToAction("GetCompanyList");
                }
                catch
                {
                    return View(company);
                }
            }
            else
            {
                return View(company);
            }
        }

        public ActionResult GetCompanyList()
        {
            return View(companyService.GetAll().AsEnumerable());
        }
        public ActionResult Delete(int id)
        {
            companyService.Delete(id);
            return RedirectToAction("GetCompanyList");
        }
        public ActionResult Edit(int id)
        {
            var company = companyService.GetById(id);
            return View(company);
        }
        [HttpPost]
        public ActionResult Edit(Company company)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    companyService.Update(company);
                    return RedirectToAction("GetCompanyList");
                }
                catch
                {
                    return View(company);
                }
            }
            else return View(company);
        }
    }
}

TestQ/Controllers/EmployeeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using TestQ.Model.Models;
using TestQ.Service.Interfaces;
using TestQ.Service.Services;
using TestQ.ViewModel;

namespace TestQ.Controllers
{
    public class EmployeeController : Controller
    {
        private IService<Employee> employeeService;
        private IService<Company> companyService;

        public EmployeeController()
        {
            employeeService = EmployeeService.Instance();
            companyService = CompanyService.Instance();
        }
        public ActionResult GetEmployeeList()
        {
            return View(employeeService.GetAll().AsEnumerable());
        }
        public ActionResult Delete(int id)
        {
            employeeService.Delete(id);
            return RedirectToAction("GetEmployeeList");
        }
        public ActionResult Create()
        {
            return View(new AddEditEmployeeViewModel
            {
                Employee = new Employee
                {
                    HiringDate = DateTime.Now,
                },
                SelectListCompanies = GetCompanyNames()
            });
        }
        [HttpPost]
        public ActionResult Create(Employee employee)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    employeeService.Add(employee);
                    return RedirectToAction("GetEmployeeList");
                }
                catch
                {
                    return View(new AddEditEmployeeViewModel
                    {
                        Employee = employee,
                        SelectListCompanies = GetCompanyNames()
                    });
                }
            }
            else
            {
                return View(new AddEditEmployeeViewModel
                {
                    Employee = employee,
                    SelectListCompanies = GetCompanyNames()
                });
            }
        }
        public ActionResult Edit(int id)
        {
            var employee = employeeService.GetById(id);
            
            return View(new AddEditEmployeeViewModel
            {
                Employee = employee,
                SelectListCompanies = GetCompanyNames(employee.CompanyId)
            });
        }
        [HttpPost]
        public ActionResult Edit(Employee employee)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    employeeService.Update(employee);
                    return RedirectToAction("GetEmployeeList");
                }
                catch(Exception ex)
                {
                    return View(new AddEditEmployeeViewModel
                    {
                        Employee = employee,
                        SelectListCompanies = GetCompanyNames(employee.CompanyId)
                    });
                }
            }
            else
            {
                return View(new AddEditEmployeeViewModel
                {
                    Employee = employee,
                    SelectListCompanies = GetCompanyNames(employee.CompanyId)
                });
            }
        }
        [NonAction]
        private List<SelectListItem> GetCompanyNames(int companyId = -1)
        {
            var companiesNameSelectListItems = new List<SelectListItem>();

            foreach (var company in companyService.GetAll())
            {
                var selectedItem = new SelectListItem()
                {
                    Text = company.Name,
                    Value = company.Id.ToString()
                };
                if (companyId!=1 && companyId == company.Id)
                {
                    selectedItem.Selected = true;
                }
                companiesNameSelectListItems.Add(selectedItem);
            }
            return companiesNameSelectListItems;
        }
    }
}

TestQ/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("MainPage", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                @Html.ActionLink("Companies", "GetCompanyList", "Company", new { area = "" }, new { @class = "navbar-brand" })
                @Html.ActionLink("Employees", "GetEmployeeList", "Employee", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Nick Yurouski TestQ Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>